name: Build Actions
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          persist-credentials: false
      - run: npm version "${{ github.ref_name }}" --no-git-tag-version --allow-same-version
        working-directory: assets
      - run: docker build -t wasm_mvg .
      - run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            --mount "type=bind,source=$(pwd),target=/workdir" \
            wasm_mvg make wasm-release
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${{ github.ref_name }}" "./build/wasm/RELEASE/wasmMVG-${{ github.ref_name }}.tgz"
